import type { BankingData } from './schema'

export function createBankingData(): BankingData {
  return {
    accounts: [
      {
        id: 'checking',
        name: 'Everyday checking',
        kind: 'Checking',
        last4: '4821',
        balance: 824550,
        rate: '0.00%',
      },
      {
        id: 'savings',
        name: 'Rainy day fund',
        kind: 'Savings',
        last4: '9012',
        balance: 1860000,
        rate: '4.10%',
      },
      {
        id: 'travel',
        name: 'Travel savings',
        kind: 'Savings',
        last4: '7734',
        balance: 325000,
        rate: '3.50%',
      },
    ],
    transactions: [
      {
        id: 'tx-1',
        accountId: 'checking',
        description: 'Whole Foods Market',
        category: 'Groceries',
        date: '2026-09-30T16:30:00Z',
        amount: -8642,
        status: 'Completed',
      },
      {
        id: 'tx-2',
        accountId: 'checking',
        description: 'Blue Bottle Coffee',
        category: 'Dining',
        date: '2026-09-30T09:00:00Z',
        amount: -650,
        status: 'Completed',
      },
      {
        id: 'tx-3',
        accountId: 'checking',
        description: 'Northstar · September salary',
        category: 'Income',
        date: '2026-09-28T09:00:00Z',
        amount: 625000,
        status: 'Completed',
      },
      {
        id: 'tx-4',
        accountId: 'checking',
        description: 'Figma',
        category: 'Subscriptions',
        date: '2026-09-26T10:00:00Z',
        amount: -1500,
        status: 'Completed',
      },
      {
        id: 'tx-5',
        accountId: 'checking',
        description: 'City apartment',
        category: 'Housing',
        date: '2026-09-25T10:00:00Z',
        amount: -185000,
        status: 'Completed',
      },
      {
        id: 'tx-6',
        accountId: 'travel',
        description: 'Airline reservation',
        category: 'Travel',
        date: '2026-09-24T13:00:00Z',
        amount: -24800,
        status: 'Pending',
      },
      {
        id: 'tx-7',
        accountId: 'savings',
        description: 'Monthly interest',
        category: 'Income',
        date: '2026-09-23T10:00:00Z',
        amount: 6250,
        status: 'Completed',
      },
      {
        id: 'tx-8',
        accountId: 'checking',
        description: 'City transit',
        category: 'Transport',
        date: '2026-09-22T08:00:00Z',
        amount: -4200,
        status: 'Completed',
      },
    ],
    cards: [
      {
        id: 'physical',
        accountId: 'checking',
        name: 'Everyday debit',
        last4: '4821',
        kind: 'Physical',
        frozen: false,
        online: true,
        limit: 300000,
        spent: 199992,
      },
      {
        id: 'virtual',
        accountId: 'checking',
        name: 'Online purchases',
        last4: '6093',
        kind: 'Virtual',
        frozen: false,
        online: true,
        limit: 50000,
        spent: 1500,
      },
    ],
  }
}
