import type { BusinessData, ChatMessage, Parcel, ParcelStatus } from './schema'
import { sortingLanes, sortLanes } from './logistics'
export { pickupLocations, sortLanes } from './logistics'
export type {
  BusinessData,
  ChatMessage,
  Employee,
  LeaveRequest,
  Parcel,
  ParcelEvent,
  ParcelStatus,
  Ticket,
  Invoice,
} from './schema'
export const chatPeople = [
  {
    id: 'alex',
    name: 'Alex Morgan',
    initials: 'AM',
    role: 'Product designer',
    online: true,
    color: 'blue',
  },
  { id: 'sam', name: 'Sam Lee', initials: 'SL', role: 'Engineer', online: true, color: 'green' },
  {
    id: 'jordan',
    name: 'Jordan Chen',
    initials: 'JC',
    role: 'Design lead',
    online: true,
    color: 'violet',
  },
  {
    id: 'riley',
    name: 'Riley Park',
    initials: 'RP',
    role: 'Operations',
    online: false,
    color: 'amber',
  },
  {
    id: 'nina',
    name: 'Nina Patel',
    initials: 'NP',
    role: 'People partner',
    online: true,
    color: 'rose',
  },
]
export const chatRooms = [
  {
    id: 'general',
    name: 'general',
    topic: 'Company updates, questions, and things worth sharing.',
    section: 'WORKSPACE',
  },
  {
    id: 'announcements',
    name: 'announcements',
    topic: 'Release notes and important workspace updates.',
    section: 'WORKSPACE',
  },
  {
    id: 'design',
    name: 'design',
    topic: 'Design reviews, component discussions, and feedback.',
    section: 'PROJECTS',
  },
  {
    id: 'engineering',
    name: 'engineering',
    topic: 'Implementation notes and engineering discussions.',
    section: 'PROJECTS',
  },
  {
    id: 'operations',
    name: 'operations',
    topic: 'Daily operations and handover notes.',
    section: 'PROJECTS',
  },
]

export const departments = ['Engineering', 'Design', 'Operations', 'People']
export const onboardingSteps = [
  'Account provisioned',
  'Documents verified',
  'Orientation scheduled',
]

export const parcelLabels: Record<ParcelStatus, string> = {
  received: 'Received',
  sorted: 'Sorted',
  transit: 'In transit',
  ready: 'Ready for pickup',
  collected: 'Collected',
  exception: 'Exception',
}

export function createBusinessData(): BusinessData {
  const message = (
    id: string,
    room: string,
    author: string,
    text: string,
    time: string,
    pinned = false,
  ): ChatMessage => ({
    id,
    room,
    author,
    text,
    time: `2026-10-02T${time}:00`,
    pinned,
    reactions: [],
  })
  const parcel = (
    id: string,
    customer: string,
    destination: string,
    status: ParcelStatus,
    code: string,
    shelf = '',
  ): Parcel => ({
    id,
    customer,
    destination,
    status,
    code,
    shelf,
    phone: '+44 7700 900123',
    lane:
      status === 'received' || status === 'exception'
        ? ''
        : sortingLanes.find((lane) => lane.destination === destination)?.label || sortLanes[0],
    items: '1 parcel · Clothing and accessories',
    weight: '1.4 kg',
    holdUntil: '2026-10-09',
    exception: '',
    events: [
      { id: `${id}-received`, label: 'Received at East London hub', time: '2026-10-02T07:15:00' },
      ...(status !== 'received'
        ? [{ id: `${id}-status`, label: parcelLabels[status], time: '2026-10-02T09:20:00' }]
        : []),
    ],
  })
  return {
    version: 1,
    messages: [
      message(
        'msg-1',
        'general',
        'jordan',
        'Morning, everyone. The new component review is ready. Please leave feedback in #design before our 14:00 sync.',
        '09:02',
        true,
      ),
      {
        ...message(
          'msg-2',
          'general',
          'sam',
          'The keyboard navigation pass is complete. Dialog focus and the mobile sidebar are looking good.',
          '09:08',
        ),
        reactions: [
          { emoji: '👍', count: 3, mine: false },
          { emoji: '🎉', count: 2, mine: false },
        ],
      },
      message(
        'msg-3',
        'general',
        'alex',
        'Thanks, Sam. I’m testing the new order workflow this morning and will share notes after lunch.',
        '09:12',
      ),
      message(
        'msg-4',
        'general',
        'nina',
        'Quick reminder: please submit next month’s leave requests by Friday so we can finish the coverage plan.',
        '09:20',
      ),
      {
        ...message(
          'msg-5',
          'general',
          'riley',
          'The sorting-center handover is documented now. We added a separate queue for label exceptions.',
          '09:34',
        ),
        reactions: [{ emoji: '✅', count: 2, mine: true }],
      },
      message(
        'msg-6',
        'general',
        'sam',
        'That will help. Could you include an example of a parcel moving from sorting to pickup?',
        '09:37',
      ),
      {
        ...message(
          'msg-7',
          'general',
          'riley',
          'Yes — PKG-1044 is a sample arrival. Receive it at Central Station, assign a shelf, and try the collection flow.',
          '09:39',
        ),
        replyTo: 'msg-6',
      },
      message(
        'msg-8',
        'design',
        'jordan',
        'Review focus: readable type, useful empty states, and consistent table actions. The minimum text size stays at 14px.',
        '08:45',
        true,
      ),
      message(
        'msg-9',
        'design',
        'alex',
        'I’ve added the profile sheet and leave approval states. The directory works as both a table and a card grid.',
        '09:05',
      ),
      message(
        'msg-10',
        'engineering',
        'sam',
        'Template data is persisted locally. Refreshing the page should keep task, message, and order changes.',
        '08:50',
      ),
      message(
        'msg-11',
        'operations',
        'riley',
        'Morning shift: use lane A1 for Central Station, B2 for East Harbor, and C3 for Northgate.',
        '07:30',
        true,
      ),
      message(
        'msg-12',
        'announcements',
        'nina',
        'Welcome to the Northstar workspace. Project discussions go in their channels; direct messages are available in the sidebar.',
        '08:00',
        true,
      ),
      message(
        'msg-13',
        'dm-sam',
        'sam',
        'Hey Alex — can you take a look at the updated sorting queue?',
        '09:10',
      ),
      message(
        'msg-14',
        'dm-sam',
        'alex',
        'Absolutely. I’ll check the scan and exception states next.',
        '09:14',
      ),
    ],
    employees: [
      {
        id: 'e-alex',
        name: 'Alex Morgan',
        email: 'alex@example.com',
        role: 'Product designer',
        department: 'Design',
        location: 'London',
        status: 'Active',
        startDate: '2024-03-18',
        manager: 'Jordan Chen',
        onboarding: [true, true, true],
      },
      {
        id: 'e-sam',
        name: 'Sam Lee',
        email: 'sam@example.com',
        role: 'Senior engineer',
        department: 'Engineering',
        location: 'London',
        status: 'Active',
        startDate: '2023-08-07',
        manager: 'Priya Shah',
        onboarding: [true, true, true],
      },
      {
        id: 'e-jordan',
        name: 'Jordan Chen',
        email: 'jordan@example.com',
        role: 'Design lead',
        department: 'Design',
        location: 'Berlin',
        status: 'Active',
        startDate: '2022-11-14',
        manager: 'Morgan Ellis',
        onboarding: [true, true, true],
      },
      {
        id: 'e-riley',
        name: 'Riley Park',
        email: 'riley@example.com',
        role: 'Operations manager',
        department: 'Operations',
        location: 'London',
        status: 'Active',
        startDate: '2023-05-22',
        manager: 'Morgan Ellis',
        onboarding: [true, true, true],
      },
      {
        id: 'e-nina',
        name: 'Nina Patel',
        email: 'nina@example.com',
        role: 'People partner',
        department: 'People',
        location: 'London',
        status: 'Active',
        startDate: '2024-01-08',
        manager: 'Morgan Ellis',
        onboarding: [true, true, true],
      },
      {
        id: 'e-omar',
        name: 'Omar Hassan',
        email: 'omar@example.com',
        role: 'Support specialist',
        department: 'Operations',
        location: 'Manchester',
        status: 'On leave',
        startDate: '2024-09-02',
        manager: 'Riley Park',
        onboarding: [true, true, true],
      },
      {
        id: 'e-priya',
        name: 'Priya Shah',
        email: 'priya@example.com',
        role: 'Engineering manager',
        department: 'Engineering',
        location: 'Berlin',
        status: 'Active',
        startDate: '2022-06-13',
        manager: 'Morgan Ellis',
        onboarding: [true, true, true],
      },
      {
        id: 'e-taylor',
        name: 'Taylor Smith',
        email: 'taylor@example.com',
        role: 'Frontend engineer',
        department: 'Engineering',
        location: 'Remote',
        status: 'Onboarding',
        startDate: '2026-10-05',
        manager: 'Priya Shah',
        onboarding: [true, false, false],
      },
    ],
    leave: [
      {
        id: 'leave-1',
        employeeId: 'e-alex',
        kind: 'Annual leave',
        start: '2026-10-12',
        end: '2026-10-16',
        status: 'Pending',
        note: 'Family trip.',
      },
      {
        id: 'leave-2',
        employeeId: 'e-sam',
        kind: 'Personal leave',
        start: '2026-10-09',
        end: '2026-10-09',
        status: 'Pending',
        note: 'Personal appointment.',
      },
      {
        id: 'leave-3',
        employeeId: 'e-omar',
        kind: 'Annual leave',
        start: '2026-10-01',
        end: '2026-10-05',
        status: 'Approved',
        note: '',
      },
    ],
    parcels: [
      parcel('PKG-1042', 'Emma Wilson', 'Central Station', 'received', '641205'),
      parcel('PKG-1043', 'Noah Clarke', 'East Harbor', 'sorted', '281634'),
      parcel('PKG-1044', 'Sofia Evans', 'Central Station', 'transit', '735290'),
      parcel('PKG-1045', 'Oliver Reed', 'Central Station', 'ready', '482193', 'A-01'),
      parcel('PKG-1046', 'Mia Brooks', 'Northgate', 'ready', '729416', 'B-02'),
      parcel('PKG-1047', 'Leo Turner', 'East Harbor', 'collected', '195842', 'A-02'),
      {
        ...parcel('PKG-1048', 'Ava Bennett', 'Central Station', 'exception', '802417'),
        exception: 'Shipping label is unreadable. Confirm destination before sorting.',
        holdFrom: 'received',
      },
      parcel('PKG-1049', 'Amir Khan', 'Northgate', 'received', '912467'),
      parcel('PKG-1050', 'Isla Hughes', 'Central Station', 'sorted', '350128'),
      parcel('PKG-1051', 'Ethan Cooper', 'East Harbor', 'transit', '643891'),
      parcel('PKG-1052', 'Grace Martin', 'Central Station', 'ready', '560213', 'A-03'),
    ],
    tickets: [
      {
        id: 'SUP-201',
        subject: 'Help with a delayed parcel',
        customer: 'Ava Bennett',
        email: 'ava@example.com',
        status: 'Open',
        priority: 'Urgent',
        assignee: 'alex',
        orderId: 'PKG-1048',
        messages: [
          {
            id: 't1-m1',
            author: 'Ava Bennett',
            text: 'My parcel hasn’t moved since this morning. Could you check whether it is still on the way to Central Station?',
            internal: false,
            time: '2026-10-02T09:15:00',
          },
          {
            id: 't1-m2',
            author: 'Riley Park',
            text: 'The label is unreadable. The parcel is in the sorting-center exception queue.',
            internal: true,
            time: '2026-10-02T09:24:00',
          },
        ],
      },
      {
        id: 'SUP-202',
        subject: 'Change my pickup location',
        customer: 'Emma Wilson',
        email: 'emma@example.com',
        status: 'Open',
        priority: 'Normal',
        assignee: 'sam',
        orderId: 'PKG-1042',
        messages: [
          {
            id: 't2-m1',
            author: 'Emma Wilson',
            text: 'Is it possible to collect my parcel from East Harbor instead? It hasn’t been dispatched yet.',
            internal: false,
            time: '2026-10-02T08:50:00',
          },
        ],
      },
      {
        id: 'SUP-203',
        subject: 'Where can I find the collection code?',
        customer: 'Oliver Reed',
        email: 'oliver@example.com',
        status: 'Pending',
        priority: 'Normal',
        assignee: 'alex',
        orderId: 'PKG-1045',
        messages: [
          {
            id: 't3-m1',
            author: 'Oliver Reed',
            text: 'The parcel is ready, but I cannot find the collection code in my messages.',
            internal: false,
            time: '2026-10-02T08:30:00',
          },
          {
            id: 't3-m2',
            author: 'Alex Morgan',
            text: 'Please check the collection notice associated with your order. We can also help at the pickup desk.',
            internal: false,
            time: '2026-10-02T08:42:00',
          },
        ],
      },
      {
        id: 'SUP-204',
        subject: 'Invoice copy requested',
        customer: 'Leo Turner',
        email: 'leo@example.com',
        status: 'Resolved',
        priority: 'Low',
        assignee: 'sam',
        orderId: 'PKG-1047',
        messages: [
          {
            id: 't4-m1',
            author: 'Leo Turner',
            text: 'Could I get a copy of the delivery invoice for my records?',
            internal: false,
            time: '2026-10-01T15:00:00',
          },
          {
            id: 't4-m2',
            author: 'Sam Lee',
            text: 'You can export the invoice from your billing page. Let us know if you need anything else.',
            internal: false,
            time: '2026-10-01T15:12:00',
          },
        ],
      },
    ],
    invoices: [
      {
        id: 'INV-2026-001',
        customer: 'Acme Studio',
        email: 'billing@acme.example',
        description: 'Workspace plan · September',
        cents: 24900,
        due: '2026-10-05',
        status: 'Sent',
        reference: '',
      },
      {
        id: 'INV-2026-002',
        customer: 'Atlas Commerce',
        email: 'finance@atlas.example',
        description: 'Delivery services · September',
        cents: 128000,
        due: '2026-09-28',
        status: 'Overdue',
        reference: '',
      },
      {
        id: 'INV-2026-003',
        customer: 'Juniper Labs',
        email: 'accounts@juniper.example',
        description: 'Workspace plan · September',
        cents: 49900,
        due: '2026-09-30',
        status: 'Paid',
        reference: 'BANK-0930',
      },
      {
        id: 'INV-2026-004',
        customer: 'Cedar & Co.',
        email: 'hello@cedar.example',
        description: 'Fulfillment services · October',
        cents: 87500,
        due: '2026-10-15',
        status: 'Draft',
        reference: '',
      },
      {
        id: 'INV-2026-005',
        customer: 'Fieldwork',
        email: 'team@fieldwork.example',
        description: 'Workspace plan · September',
        cents: 24900,
        due: '2026-10-07',
        status: 'Sent',
        reference: '',
      },
      {
        id: 'INV-2026-006',
        customer: 'Orbit Supply',
        email: 'billing@orbit.example',
        description: 'Delivery services · September',
        cents: 162500,
        due: '2026-09-26',
        status: 'Paid',
        reference: 'BANK-0926',
      },
    ],
  }
}
