import type { TemplatePageId } from '../templates/catalog'

export type Category =
  'All components' | 'Actions' | 'Forms' | 'Display' | 'Feedback' | 'Navigation'

function entry<Id extends string>(
  id: Id,
  name: string,
  category: Category,
  description: string,
  exports: string[],
  example: string,
  props: string,
) {
  const file = id === 'toast' ? 'sonner' : id
  return {
    id,
    name,
    category,
    description,
    detail: description,
    file,
    code: `import { ${exports.join(', ')} } from "@/components/ui/${file}"\n\n${example}`,
    props,
  }
}

export const catalog = [
  entry(
    'button',
    'Button',
    'Actions',
    'Actions with variants, sizes, and loading states.',
    ['Button'],
    '<Button variant="default">Save changes</Button>\n<Button variant="outline">Cancel</Button>\n<Button loading>Saving</Button>',
    'variant: default | secondary | outline | ghost | destructive | link | accent\nsize: default | sm | lg | icon\nasChild?: boolean\nloading?: boolean\nNative button props and ref',
  ),
  entry(
    'input',
    'Input',
    'Forms',
    'Single-line text input with native form behavior.',
    ['Input'],
    '<label htmlFor="email">Email address</label>\n<Input id="email" type="email" placeholder="you@example.com" required />',
    'Native input props and ref\naria-invalid?: boolean\ndisabled?: boolean',
  ),
  entry(
    'checkbox',
    'Checkbox',
    'Forms',
    'Checked, unchecked, and indeterminate selection.',
    ['Checkbox'],
    '<div className="flex items-center gap-3">\n  <Checkbox id="terms" defaultChecked />\n  <label htmlFor="terms">Accept terms</label>\n</div>',
    'checked?: boolean | "indeterminate"\ndefaultChecked?: boolean\nonCheckedChange?: (checked) => void\nname?: string\nrequired?: boolean\ndisabled?: boolean',
  ),
  entry(
    'textarea',
    'Textarea',
    'Forms',
    'Multi-line input for longer text.',
    ['Textarea'],
    '<label htmlFor="notes">Notes</label>\n<Textarea id="notes" placeholder="Add a note…" />',
    'Native textarea props and ref\nrows?: number\nmaxLength?: number\naria-invalid?: boolean',
  ),
  entry(
    'select',
    'Select',
    'Forms',
    'A keyboard-accessible list of options.',
    ['Select', 'SelectTrigger', 'SelectValue', 'SelectContent', 'SelectItem'],
    '<Select defaultValue="reader">\n  <SelectTrigger aria-label="Role"><SelectValue /></SelectTrigger>\n  <SelectContent>\n    <SelectItem value="reader">Reader</SelectItem>\n    <SelectItem value="editor">Editor</SelectItem>\n  </SelectContent>\n</Select>',
    'value?: string\ndefaultValue?: string\nonValueChange?: (value: string) => void\nname?: string\ndisabled?: boolean',
  ),
  entry(
    'switch',
    'Switch',
    'Forms',
    'An on/off setting with immediate feedback.',
    ['Switch'],
    '<Switch aria-label="Email notifications" defaultChecked />',
    'checked?: boolean\ndefaultChecked?: boolean\nonCheckedChange?: (checked: boolean) => void\nname?: string\ndisabled?: boolean',
  ),
  entry(
    'radio-group',
    'Radio Group',
    'Forms',
    'Choose one option from a set.',
    ['RadioGroup', 'RadioGroupItem'],
    '<RadioGroup defaultValue="monthly" aria-label="Billing interval">\n  <div className="flex items-center gap-3">\n    <RadioGroupItem value="monthly" id="monthly" />\n    <label htmlFor="monthly">Monthly</label>\n  </div>\n  <div className="flex items-center gap-3">\n    <RadioGroupItem value="yearly" id="yearly" />\n    <label htmlFor="yearly">Yearly</label>\n  </div>\n</RadioGroup>',
    'value?: string\ndefaultValue?: string\nonValueChange?: (value: string) => void\norientation?: horizontal | vertical',
  ),
  entry(
    'slider',
    'Slider',
    'Forms',
    'Select a value or range with keyboard support.',
    ['Slider'],
    '<Slider defaultValue={[50]} max={100} step={1} aria-label="Volume" />',
    'value?: number[]\ndefaultValue?: number[]\nonValueChange?: (values: number[]) => void\nonValueCommit?: (values: number[]) => void\nmin?: number\nmax?: number\nstep?: number\nthumbLabels?: string[]',
  ),
  entry(
    'tabs',
    'Tabs',
    'Navigation',
    'Organize related views in labeled panels.',
    ['Tabs', 'TabsList', 'TabsTrigger', 'TabsContent'],
    '<Tabs defaultValue="account">\n  <TabsList aria-label="Settings">\n    <TabsTrigger value="account">Account</TabsTrigger>\n    <TabsTrigger value="security">Security</TabsTrigger>\n  </TabsList>\n  <TabsContent value="account">Account settings</TabsContent>\n  <TabsContent value="security">Security settings</TabsContent>\n</Tabs>',
    'value?: string\ndefaultValue?: string\nonValueChange?: (value: string) => void\norientation?: horizontal | vertical',
  ),
  entry(
    'accordion',
    'Accordion',
    'Display',
    'Expand and collapse sections of content.',
    ['Accordion', 'AccordionItem', 'AccordionTrigger', 'AccordionContent'],
    '<Accordion type="single" collapsible>\n  <AccordionItem value="accessibility">\n    <AccordionTrigger>Keyboard support</AccordionTrigger>\n    <AccordionContent>Use Tab to focus and Enter to expand.</AccordionContent>\n  </AccordionItem>\n</Accordion>',
    'type: single | multiple\nvalue?: string | string[]\ncollapsible?: boolean (single mode)\nonValueChange?: (value) => void',
  ),
  entry(
    'badge',
    'Badge',
    'Display',
    'Text labels for status and metadata.',
    ['Badge'],
    '<Badge tone="success">Published</Badge>\n<Badge tone="warning">Pending</Badge>\n<Badge tone="danger">Failed</Badge>',
    'tone: neutral | success | warning | danger | info\nNative span props',
  ),
  entry(
    'card',
    'Card',
    'Display',
    'A container with header, content, and footer slots.',
    ['Card', 'CardHeader', 'CardTitle', 'CardDescription', 'CardContent'],
    '<Card>\n  <CardHeader>\n    <CardTitle>Project settings</CardTitle>\n    <CardDescription>Manage your workspace.</CardDescription>\n  </CardHeader>\n  <CardContent>Settings content</CardContent>\n</Card>',
    'Card / CardHeader / CardContent / CardFooter: div props\nCardTitle: h3 props\nCardDescription: p props',
  ),
  entry(
    'dialog',
    'Dialog',
    'Feedback',
    'A modal with focus trapping and Escape dismissal.',
    [
      'Dialog',
      'DialogTrigger',
      'DialogContent',
      'DialogHeader',
      'DialogTitle',
      'DialogDescription',
    ],
    '<Dialog>\n  <DialogTrigger>Open settings</DialogTrigger>\n  <DialogContent>\n    <DialogHeader>\n      <DialogTitle>Settings</DialogTitle>\n      <DialogDescription>Update your preferences.</DialogDescription>\n    </DialogHeader>\n  </DialogContent>\n</Dialog>',
    'Dialog: open?, defaultOpen?, onOpenChange?\nDialogTrigger / DialogClose: asChild?\nDialogContent: Radix content props\nCompose DialogTitle and DialogDescription for accessible naming.\nOptional title/description strings are also supported.',
  ),
  entry(
    'alert',
    'Alert',
    'Feedback',
    'Persistent feedback within the page.',
    ['Alert', 'AlertTitle', 'AlertDescription'],
    '<Alert>\n  <AlertTitle>Changes saved</AlertTitle>\n  <AlertDescription>Your settings have been updated.</AlertDescription>\n</Alert>',
    'variant: default | destructive\nNative div props\nDefault role: alert',
  ),
  entry(
    'alert-dialog',
    'Alert Dialog',
    'Feedback',
    'Confirmation for destructive or significant actions.',
    [
      'AlertDialog',
      'AlertDialogTrigger',
      'AlertDialogContent',
      'AlertDialogTitle',
      'AlertDialogDescription',
      'AlertDialogFooter',
      'AlertDialogCancel',
      'AlertDialogAction',
    ],
    '<AlertDialog>\n  <AlertDialogTrigger>Delete draft</AlertDialogTrigger>\n  <AlertDialogContent>\n    <AlertDialogTitle>Delete draft?</AlertDialogTitle>\n    <AlertDialogDescription>This cannot be undone.</AlertDialogDescription>\n    <AlertDialogFooter>\n      <AlertDialogCancel>Cancel</AlertDialogCancel>\n      <AlertDialogAction onClick={() => console.log("Deleted")}>Delete</AlertDialogAction>\n    </AlertDialogFooter>\n  </AlertDialogContent>\n</AlertDialog>',
    'open?: boolean\nonOpenChange?: (open: boolean) => void\nCancel receives initial focus.\nOutside clicks do not dismiss.',
  ),
  entry(
    'avatar',
    'Avatar',
    'Display',
    'Profile imagery with a text fallback.',
    ['Avatar', 'AvatarImage', 'AvatarFallback'],
    '<Avatar>\n  <AvatarImage src="/avatar.jpg" alt="Alex Morgan" />\n  <AvatarFallback>AM</AvatarFallback>\n</Avatar>',
    'Avatar: Radix root props\nAvatarImage: src, alt, onLoadingStatusChange\nAvatarFallback: delayMs?',
  ),
  entry(
    'breadcrumb',
    'Breadcrumb',
    'Navigation',
    'Linked ancestors and the current page.',
    [
      'Breadcrumb',
      'BreadcrumbList',
      'BreadcrumbItem',
      'BreadcrumbLink',
      'BreadcrumbSeparator',
      'BreadcrumbPage',
    ],
    '<Breadcrumb>\n  <BreadcrumbList>\n    <BreadcrumbItem><BreadcrumbLink href="#overview">Home</BreadcrumbLink></BreadcrumbItem>\n    <BreadcrumbSeparator />\n    <BreadcrumbItem><BreadcrumbPage>Settings</BreadcrumbPage></BreadcrumbItem>\n  </BreadcrumbList>\n</Breadcrumb>',
    'Native nav / ol / li / a / span props\nBreadcrumbLink: asChild?\nBreadcrumbPage sets aria-current="page"',
  ),
  entry(
    'collapsible',
    'Collapsible',
    'Display',
    'A disclosure for supplementary content.',
    ['Collapsible', 'CollapsibleTrigger', 'CollapsibleContent'],
    '<Collapsible>\n  <CollapsibleTrigger>Show dependencies</CollapsibleTrigger>\n  <CollapsibleContent>react, radix-ui, tailwindcss</CollapsibleContent>\n</Collapsible>',
    'open?: boolean\ndefaultOpen?: boolean\nonOpenChange?: (open: boolean) => void\nCollapsibleTrigger: asChild?',
  ),
  entry(
    'command',
    'Command',
    'Navigation',
    'Searchable actions with keyboard selection.',
    ['Command', 'CommandInput', 'CommandList', 'CommandEmpty', 'CommandItem'],
    '<Command label="Quick actions">\n  <CommandInput placeholder="Search actions…" />\n  <CommandList>\n    <CommandEmpty>No results.</CommandEmpty>\n    <CommandItem onSelect={() => console.log("New project")}>New project</CommandItem>\n    <CommandItem onSelect={() => console.log("Settings")}>Settings</CommandItem>\n  </CommandList>\n</Command>',
    'Command: label, value?, onValueChange?, filter?\nCommandInput: value?, onValueChange?\nCommandItem: value?, onSelect?, disabled?, keywords?',
  ),
  entry(
    'dropdown-menu',
    'Dropdown Menu',
    'Actions',
    'Actions, checkboxes, radio items, and submenus.',
    ['DropdownMenu', 'DropdownMenuTrigger', 'DropdownMenuContent', 'DropdownMenuItem'],
    '<DropdownMenu>\n  <DropdownMenuTrigger>Project actions</DropdownMenuTrigger>\n  <DropdownMenuContent>\n    <DropdownMenuItem onSelect={() => console.log("Duplicated")}>Duplicate</DropdownMenuItem>\n    <DropdownMenuItem disabled>Archive</DropdownMenuItem>\n  </DropdownMenuContent>\n</DropdownMenu>',
    'DropdownMenu: open?, onOpenChange?, modal?\nContent: align?, side?, sideOffset?\nItem: onSelect?, disabled?\nCheckboxItem, RadioGroup/RadioItem, Sub/SubTrigger/SubContent supported.',
  ),
  entry(
    'field',
    'Field',
    'Forms',
    'Group a label, input, description, and error.',
    ['Field', 'FieldLabel', 'FieldDescription'],
    '<Field id="username">\n  <FieldLabel>Username</FieldLabel>\n  <input id="username" aria-describedby="username-description" />\n  <FieldDescription>Use letters and numbers.</FieldDescription>\n</Field>',
    'Field: id?, div props\nFieldLabel: label props, htmlFor inferred\nFieldDescription: p props, id inferred\nFieldError: p props, role=alert\nuseField(): { id, descriptionId, errorId }',
  ),
  entry(
    'label',
    'Label',
    'Forms',
    'An accessible label connected to a control.',
    ['Label'],
    '<Label htmlFor="name">Full name</Label>\n<input id="name" autoComplete="name" />',
    'htmlFor?: string\nNative label props and ref',
  ),
  entry(
    'pagination',
    'Pagination',
    'Navigation',
    'Previous, next, and numbered page links.',
    ['Pagination', 'PaginationContent', 'PaginationItem', 'PaginationLink', 'PaginationNext'],
    '<Pagination>\n  <PaginationContent>\n    <PaginationItem><PaginationLink href="?page=1" isActive>1</PaginationLink></PaginationItem>\n    <PaginationItem><PaginationLink href="?page=2">2</PaginationLink></PaginationItem>\n    <PaginationItem><PaginationNext href="?page=2" /></PaginationItem>\n  </PaginationContent>\n</Pagination>',
    'PaginationLink: isActive?, native anchor props\nPaginationPrevious / Next: anchor props\nPaginationEllipsis: more-pages indicator',
  ),
  entry(
    'popover',
    'Popover',
    'Feedback',
    'Anchored content with focus management.',
    ['Popover', 'PopoverTrigger', 'PopoverContent'],
    '<Popover>\n  <PopoverTrigger>Display settings</PopoverTrigger>\n  <PopoverContent>Adjust the display settings here.</PopoverContent>\n</Popover>',
    'open?: boolean\nonOpenChange?: (open: boolean) => void\nContent: align?, side?, sideOffset?\nTrigger / Close: asChild?',
  ),
  entry(
    'progress',
    'Progress',
    'Feedback',
    'A labeled, determinate progress indicator.',
    ['Progress'],
    '<Progress value={68} label="Upload progress" />',
    'value: number (clamped to 0–100)\nlabel: string\nNative div props',
  ),
  entry(
    'scroll-area',
    'Scroll Area',
    'Display',
    'A scrollable region with consistent scrollbars.',
    ['ScrollArea'],
    '<ScrollArea className="h-48 rounded-md border p-4" aria-label="Activity">\n  {Array.from({ length: 20 }, (_, i) => <p key={i}>Item {i + 1}</p>)}\n</ScrollArea>',
    'Radix ScrollArea root props\nSet an explicit height on the root.\nScrollBar: orientation?',
  ),
  entry(
    'separator',
    'Separator',
    'Display',
    'Horizontal or vertical content separation.',
    ['Separator'],
    '<Separator />\n<div className="h-8"><Separator orientation="vertical" /></div>',
    'orientation: horizontal | vertical\ndecorative?: boolean (default true)\nRadix separator props',
  ),
  entry(
    'sheet',
    'Sheet',
    'Feedback',
    'A side panel for editing or secondary workflows.',
    ['Sheet', 'SheetTrigger', 'SheetContent', 'SheetHeader', 'SheetTitle', 'SheetDescription'],
    '<Sheet>\n  <SheetTrigger>Edit profile</SheetTrigger>\n  <SheetContent>\n    <SheetHeader>\n      <SheetTitle>Profile</SheetTitle>\n      <SheetDescription>Update your personal details.</SheetDescription>\n    </SheetHeader>\n  </SheetContent>\n</Sheet>',
    'Sheet: open?, onOpenChange?\nSheetContent: side?: left | right\nTrigger / Close: asChild?\nInclude SheetTitle and SheetDescription.',
  ),
  entry(
    'skeleton',
    'Skeleton',
    'Feedback',
    'A placeholder that preserves loading layout.',
    ['Skeleton'],
    '<div role="status" aria-label="Loading profile">\n  <Skeleton className="size-10 rounded-full" />\n  <Skeleton className="mt-3 h-4 w-40" />\n</div>',
    'Native div props\nDecorative: aria-hidden=true\nPair with an application-level loading announcement.',
  ),
  entry(
    'table',
    'Table',
    'Display',
    'Semantic table elements with overflow handling.',
    ['Table', 'TableCaption', 'TableHeader', 'TableRow', 'TableHead', 'TableBody', 'TableCell'],
    '<Table>\n  <TableCaption>Recent invoices</TableCaption>\n  <TableHeader><TableRow><TableHead>Invoice</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader>\n  <TableBody><TableRow><TableCell>INV-001</TableCell><TableCell>$120.00</TableCell></TableRow></TableBody>\n</Table>',
    'Native table / thead / tbody / tfoot / tr / th / td / caption props\nTable adds an overflow wrapper.\nCompose sorting and selection in your application.',
  ),
  entry(
    'toast',
    'Toast',
    'Feedback',
    'Transient notifications with actions and dismissal.',
    ['Toaster', 'toast'],
    '// Mount once near your application root:\n<Toaster />\n\n// From an event handler:\ntoast.success("Changes saved", {\n  description: "Your profile has been updated.",\n})',
    'Toaster: Sonner ToasterProps\ntoast(message, options?)\ntoast.success / error / warning / info\ntoast.promise / dismiss\nMount one Toaster per application.',
  ),
  entry(
    'toggle',
    'Toggle',
    'Actions',
    'A two-state button with pressed semantics.',
    ['Toggle'],
    '<Toggle aria-label="Bold">B</Toggle>',
    'pressed?: boolean\ndefaultPressed?: boolean\nonPressedChange?: (pressed: boolean) => void\ndisabled?: boolean',
  ),
  entry(
    'toggle-group',
    'Toggle Group',
    'Actions',
    'Single or multiple selection within a button group.',
    ['ToggleGroup', 'ToggleGroupItem'],
    '<ToggleGroup type="single" defaultValue="left" aria-label="Alignment">\n  <ToggleGroupItem value="left">Left</ToggleGroupItem>\n  <ToggleGroupItem value="center">Center</ToggleGroupItem>\n  <ToggleGroupItem value="right">Right</ToggleGroupItem>\n</ToggleGroup>',
    'type: single | multiple\nvalue?: string | string[]\ndefaultValue?: string | string[]\nonValueChange?: (value) => void\nItem: value, disabled?',
  ),
  entry(
    'tooltip',
    'Tooltip',
    'Feedback',
    'Supplementary text on hover or keyboard focus.',
    ['Tooltip', 'TooltipTrigger', 'TooltipContent'],
    '<Tooltip>\n  <TooltipTrigger>Save</TooltipTrigger>\n  <TooltipContent>Save changes to this project</TooltipContent>\n</Tooltip>',
    'Tooltip: Radix root props\nTooltipProvider: delayDuration?, skipDelayDuration?\nTooltipContent: side?, sideOffset?, align?\nOptional content prop supports a single focusable child.',
  ),
]

export type CatalogEntry = (typeof catalog)[number]
export type ComponentId = CatalogEntry['id']
export const categories: Category[] = [
  'All components',
  'Actions',
  'Forms',
  'Display',
  'Feedback',
  'Navigation',
]
export const pages = [
  { id: 'overview', name: 'Overview', group: 'Getting started' },
  { id: 'installation', name: 'Installation', group: 'Getting started' },
  { id: 'templates', name: 'All templates', group: 'Templates' },
  { id: 'principles', name: 'Design principles', group: 'Foundations' },
  { id: 'colors', name: 'Colors', group: 'Foundations' },
  { id: 'typography', name: 'Typography', group: 'Foundations' },
  { id: 'spacing', name: 'Spacing & layout', group: 'Foundations' },
  { id: 'motion', name: 'Motion', group: 'Foundations' },
  { id: 'components', name: 'All components', group: 'Components' },
  { id: 'changelog', name: 'Changelog', group: 'Resources' },
  { id: 'research', name: 'Reference notes', group: 'Resources' },
] as const
export type DocPageId = (typeof pages)[number]['id']
export type PageId = DocPageId | `component/${ComponentId}` | TemplatePageId
